Weightable/config/routes.rb
Weightable::Application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'},
                     :controllers => { :registrations => "registrations" } 

  resources :users, only: [:show, :index, :edit, :update]
  resources :weigh_ins, only: [:new, :create, :show]
  resources :friendships
  resources :truckins, only: [:new, :create]



  get "/users/:id/success", to: 'users#success', as: "success" 

  post 'likes/:resource_name/:resource_id' => "likes#create",  :as => 'like' 

  # If user is not signed in, this redirects to sign in  page
  unauthenticated do
    root to: 'layouts#home'
  end
  
end

Weightable/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  include Amistad::FriendModel

  include Likeable::UserMethods
 
  has_many :truckins, through: :weigh_ins

  has_many :weigh_ins, :order => 'created_at DESC' do
  
  # Used to determine the goal in the weighin model
  # Will allow user to only post 1/day
    def today
      where(:created_at => (Time.now.beginning_of_day..Time.now))
    end
  end
  
  #validations

  validates :start_weight, :goal_weight, :first_name, :last_name, :about, presence: true
 

  # Sets the full name of the user

  def name
    "#{first_name} #{last_name}"
  end

  # Checks to see if user has added goal weight and checkins
  # and then
  # Displays the weight to go until user meets current goal

  def weight_until_goal
    if weigh_ins.count > 0 && goal_weight > 0
      weigh_ins.first.current_weight - goal_weight
    elsif goal_weight > 0
      start_weight - goal_weight
    end
  end

  # Allows user to upload a profile image
  
  mount_uploader :user_image, ImageUploader

end

Weightable/app/models/weigh_in.rb
class WeighIn < ActiveRecord::Base
	belongs_to :user
	has_many :truckins
  include Likeable

  # Allows user to upload an image with weighin
  
  mount_uploader :weigh_in_image, ImageUploader

  validate :user_quota, :on => :create

  def user_quota
    if user.weigh_ins.today.count >= 1
      errors.add(:base, "Only 1 checkin allowed per day!")
    end
  end

end

Weightable/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    [:name, :profile_pic, :start_weight, :goal_weight, :about, :first_name, :last_name].each do |field|
      devise_parameter_sanitizer.for(:account_update) << field
      devise_parameter_sanitizer.for(:sign_up) << field
    end
  end

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

end

Weightable/app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  before_filter :authenticate_user!

  def index
    @friends = current_user.friends
    @pending_invited_by = current_user.pending_invited_by
    @pending_invited = current_user.pending_invited
  end

  def create
    @friend = User.find(params[:user_id])
    @friendship_created = current_user.invite(@friend)

    if @friendship_created
      flash[:notice] = "A friendship request was sent to #{@friend.name}"
      redirect_to users_path
    end
  end

  def update
    @friend = User.find(params[:id])
    @friendship_approved = current_user.approve(@friend)
    @friends = current_user.friends
    @pending_invited_by = current_user.pending_invited_by
    flash[:notice] = "Friendship approved"
    redirect_to users_path
  end

  def destroy
    @friend = User.find(params[:id])
    @friendship = current_user.send(:find_any_friendship_with, @friend)
    if @friendship
      @friendship.delete
      @removed = true
      flash[:notice] = "This friendship request has been denied"
      redirect_to users_path
    end
  end

end

Weightable/app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  before_filter :authenticate_user!

end

Weightable/app/controllers/likes_controller.rb
 class LikesController < ApplicationController

    def create
      target = Likeable.find_by_resource_id(params[:resource_name], params[:resource_id])
      current_user.like!(target)
      redirect_to :back, :notice => 'success'
    end

    def destroy
      target = Likeable.find_by_resource_id(params[:resource_name], params[:resource_id])
      current_user.unlike!(target)
      redirect_to :back, :notice => 'success'
    end
 end

Weightable/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

end

Weightable/app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

end

Weightable/app/controllers/truckins_controller.rb
class TruckinsController < ActionController::Base

  def show
  end

  def new
    @truckin = Truckin.new
    @truckins.users_id = current_user.id
    @truckins.weigh_ins_id = weigh_in.id
    @user = User.find(current_user)
  end

  def create
    @user = User.find(current_user)
   
  end

  private 

    # Never trust parameters from the scary internet, only allow the white list through.
    def truckins_params
      params.require(:truckins).permit(:users_id, :weigh_ins_id)
    end
end

Weightable/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
  end

  def index
  	@users = User.paginate(:page => params[:page], :per_page => 20)
  end

  def edit
    correct_user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path
  end

  def success 
    @user= User.find(params[:id])
  end  

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :about, :start_weight, :goal_weight, :user_image)
    end

    # Before filters

    def correct_user
      @user = User.find(params[:id])
      redirect_to(user_path) unless current_user.id == @user.id
    end

end

Weightable/app/controllers/weigh_ins_controller.rb
class WeighInsController < ActionController::Base

  def show
  end

  def new
    @weigh_in = WeighIn.new
    @weigh_in.user_id = current_user.id
    @user = User.find(current_user)
  end

  def create
    @user = User.find(current_user)
    @weigh_in = current_user.weigh_ins.build(weigh_in_params)
    


    respond_to do |format|
      
      if  @weigh_in.save 
          if (@user.goal_weight - @weigh_in.current_weight) <= 0 

           format.html {redirect_to success_path(current_user.id), notice: 'WeighIn was succesfully created.' }
          
          else  
           format.html {redirect_to user_path(current_user.id), notice: 'WeighIn was succesfully created.' }
         end
      else
      format.html {redirect_to user_path(current_user.id), notice: 'You can only have one weigh in per day.' }
      end
    end
  end

  private 

    # Never trust parameters from the scary internet, only allow the white list through.
    def weigh_in_params
      params.require(:weigh_in).permit(:current_weight, :weigh_in_image, :user_id)
    end
end

Weightable/app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def deny_access
    redirect_to new_user_session_path, :notice => 'Please sign in to access this page.'
  end

  def current_user?
    user == current_user
  end
end

Weightable/app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user?(user)
    user == current_user
  end
end

Weightable/app/helpers/users_helper.rb
module UsersHelper

end

Weightable/app/views/layouts/_header.html.erb
<!-- navigation bar -->
<% if user_signed_in? %>
  <nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to "Who's on the Road?", users_path, { :class => 'navbar-brand' }%>
    </div>
    <!-- sign out link on the right side -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><% if current_user == @user %>
          <%= link_to 'Edit Profile', edit_user_path(current_user.id) %>
        </li>
        <% else %>
        <li>
          <%= link_to 'My Profile', user_path(current_user.id) %>
        <% end %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>
<% end %>

Weightable/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weightable</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= render 'layouts/header' %>
  <%= yield %>
</div>
</body>
</html>

Weightable/app/views/layouts/home.html.erb
<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>
  <div><%= f.submit "Sign up" %></div>
<% end %>

Weightable/app/views/layouts/users.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
      <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
      <%= csrf_meta_tags %>
      <meta charset="UTF-8">
        <!-- scale screens correctly -->
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Weightable | Weightloss for Men</title>

      <!-- put in font awesome -->
      <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

      <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
      
      <!-- allow usage of Highcharts for graphing -->
      <script src="http://code.highcharts.com/highcharts.js"></script>
      <%= javascript_include_tag "jquery-1.4.2.min", "rails", "highcharts" %>
    </head>
<body>
  <div class="container">

    <%= render 'layouts/header' %>
    <% if notice || alert %>

      <p class=”notice”><%= notice %></p>

      <p class=”alert”><%= alert %></p>

    <% end %>

    <%= yield %>

  </div> <!-- close container -->

</body>
</html>

Weightable/app/views/layouts/weigh_ins.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
      <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
      <%= csrf_meta_tags %>
        <meta charset="UTF-8">
        <!-- scale screens correctly -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>Weightable | Weightloss for Men</title>

        <!-- put in font awesome -->
        <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    </head>
<body>
  <div class="container">
  <%= render 'layouts/header' %>
   
    <% if notice || alert %>

      <p class=”notice”><%= notice %></p>

      <p class=”alert”><%= alert %></p>

    <% end %>
    </br>
    </br>
    <%= yield %>

  </div> <!-- close container -->

  <!--<script src= 'app/assets/javascripts/weigh_ins.js'></script>-->

</body>
</html>

Weightable/app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  </br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  </br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  </br>
  <%= f.label :start_weight %>
  <%= f.text_field :start_weight %>
  </br>
  <%= f.label :goal_weight %>
  <%= f.text_field :goal_weight %>
  </br>
  <%= f.label :about %>
  <%= f.text_field :about %>
  </br>
  <%= f.label :user_image %>
  <%= f.file_field :user_image %>

  <%= f.submit %>
<% end %>

</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

Weightable/app/views/users/index.html.erb
<head>
<link href='http://fonts.googleapis.com/css?family=Alegreya+SC:400,900italic' rel='stylesheet' type='text/css'>
</head>

<body>
<div id= "index_background">
  <div id= "index_text_background"
    <strong><h1>THE GANG</h1></strong>
  </div>
</div>

</br>
</br>
</br>

<!-- Add in page splits at 20 users -->

<%= will_paginate @users %>

<!-- List of current users -->
<% @users.each do |user| %>
  <% if current_user != user %>
    <div class='row'>
      <div class="index_user">
        <div class='col-sm-2 col-xs-3'>
          <%= image_tag user.user_image.url(:small), :class => 'img-rounded' %>
        </div>
        <div class='col-sm-8 col-xs-9'>
          <h4><%= link_to user.name, user_path(user.id)%></h4>
          <%= user.about.truncate(50) %>
          <% if current_user.friend_with?(user) %>
            <p>Friends</p>
          <% elsif current_user.invited?(user) %>
            <p>Friendship Pending</p>
          <% elsif current_user.invited_by?(user) %>
            <%= link_to "Accept Friend", friendship_path(user), :method => "put", :class => 'btn btn-mini' %>
            <%= link_to "Decline Friend", friendship_path(user), :method => 'delete', :class => 'btn btn-mini' %>
          <% else %>
            <%= link_to "Add friend", friendships_path(:user_id => user), :method => "post", :class => 'btn btn-mini' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>
<%= will_paginate @users %>
</body>

Weightable/app/views/users/show.html.erb
<!-- row 1 -->
  <div class="row first">
    <div class="col-xs-4 col-lg-3">
      <!-- profile pic -->
      <div>
        <% if @user.user_image.present? %>
            <%= image_tag @user.user_image.url(:medium).to_s, :class => 'img-thumbnail' %>
        <% else %>
          <img src="http://dummyimage.com/250x300&text=Add a profile picture!" alt="User Profile" class="img-responsive" alt="Responsive image"/> 
        <% end %>
      </div>
      <!-- user's name -->
      <div class="name"><p><%= @user.name %></p>
      </div>
    </div>
    <div class="col-xs-8 col-lg-9">
      <!-- Status statement -->
      <div class="row">
        <div class="col-xs-12">
          <h2 class="status">
            <% if @user.weigh_ins.count != nil && @user.goal_weight != nil %>
              I've got <%= @user.weight_until_goal %> lbs to go and I'm gettin' er done!
            <% elsif current_user.id != @user.id %>
              <%= @user.first_name %> hasn't added a goal weight yet. Maybe <%= @user.first_name %> needs some encouragement!
            <% else %>
              Add a goal weight!
            <% end %>
          </h2>
        </div>
      </div>
      <% if current_user.id == @user.id && @user.goal_weight != nil %>
        <div class="row">
          <div class="col-xs-12 weight-check-btn">
            <a href='/weigh_ins/new'><img src = "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTegOpHN8p5sWDIibx9Tsptu3KO-WfG95mdzP8JlJFNIVzbS7zo" ></a>
          </div>
        </div>
      <% end %>
    </div> 
  </div>
<!-- row 2 -->
<div class="row">
  <div class="col-lg-9 col-lg-push-3">
  <% if current_user.friend_with?(@user) || current_user == @user %>
    <% @user.weigh_ins.each do |weigh_in| %>
      <!-- post 1 -->
      <div class="row post">
        <!-- post image -->
        <div class="col-s-0 col-lg-4">
          <%= image_tag weigh_in.weigh_in_image.url(:thumb), :class => 'img-rounded' %>
        </div>
        <!-- post content -->
        <div class="col-xs-10 col-lg-8">
          <!-- weight update -->
          <div class="row">
            <div class="col-lg-12">
              <p>
                <% if weigh_in.created_at.to_date == Date.today %>
                    Today I weighed <%= weigh_in.current_weight %> lbs!
                <% else %>
                  On <%= weigh_in.created_at.to_date.to_formatted_s(:rfc822) %>, I weighed <%= weigh_in.current_weight %> lbs
                <% end %>
              </p>
            </div>
          </div>
          <!-- keep on truckin -->
          <div class="row">
            <div class="col-lg-11">
              <p><strong class= "keep_number"><%= weigh_in.like_count%></strong> buckaroos have said "Keep on Truckin!"</p>

              <input type="hidden" name="truck_in_val" value="<%= weigh_in.id %>">

            </div>
            <div class="col-lg-1">
              <button type="button" class="btn btn-sm truckin_button"><%= link_to "Keep on truckin!!", like_path(:resource_name => weigh_in.class, :resource_id => weigh_in.id), :method => :post%></button>
            </div>
          </div> <!-- end keep on truckin -->
        </div> <!-- end post content -->
      </div> <!-- end post -->
    <% end %>
    <% else %>
      <h3>You need to be connected with <%= @user.name %> to view their checkins </h3>
    <% end %>
  </div>

<!-- start user about section -->
  <div class="col-lg-3 col-lg-pull-9">
    <% if current_user.friend_with?(@user) %>
      <p>Friends</p>
    <% elsif current_user.invited?(@user) %>
      <p>Friendship Pending</p>
    <% elsif current_user.invited_by?(@user) %>
      <%= link_to "Accept Friend", friendship_path(@user), :method => "put", :class => 'btn btn-mini' %>
      <%= link_to "Decline Friend", friendship_path(@user), :method => 'delete', :class => 'btn btn-mini' %>
    <% else %>
      
    <% end %>
      <h3>About <%= @user.first_name %></h3>
      <p><%= @user.about %></p>
      <h4>My Weightable Friends</h4>
      <% @user.friends.each do |friend| %>
        <img src="<%= friend.user_image%>" height="42" width="42">
        <%= link_to friend.name, user_path(friend.id) %> 
      </br>
      <% end %>
  </div>

Weightable/app/views/users/success.html.erb
<h1> Congratulations! Things that are awesome now includes you.  </h1>

<%= form_for @user do |f| %>
<%= f.label "Would you like to set a new goal?" %><br />
<%= f.text_field :goal_weight %>
<br/>
<br/>
<br/>
<%= f.submit "submit" %>
<%end%>

Weightable/app/views/weigh_ins/new.html.erb
<div class="row">
  <div class="col-lg-6">
    <img src="http://1.bp.blogspot.com/_5vmqQqvvTpQ/TPeo8Lk9LkI/AAAAAAAAAME/G0RLkfubh04/s1600/erectile-dysfunction-s15-man-on-scale.jpg" class="img-responsive" alt="Responsive image">
  </div>
  <div class="col-lg-6" id= "content">
    <div id= "weigh_in">
      <div class="weigh_in_header">
        <h1> Time for a Weight Check!</h2>
      </div>

      <div class="weigh_in-form">
        <%= form_for @weigh_in do |f| %>

          <%= f.label "How much do you weigh today?" %><br />
          <%= f.text_field :current_weight %>
          <br />
          <br />
          <%= f.label "Add an image for this weigh in" %>
          <%= f.file_field :weigh_in_image %>

          <% f.hidden_field :user_id %>
          <br />
          <%= f.submit "submit" %>
        <% end %>
      </div>
    </div>

    <div id= "success">
    
     
    <div> 

  </div>

</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>